### ISSUE TITLE
why?~~你的仓库也被干了？~~~

### ISSUE THREAD

**Issue by wanghlstar** [EvineDeng/EvineDeng#1]
why?~~你的仓库也被干了？~~~
LXK 也没了~~~

**Comment by EvineDeng** [comment]
都被干了

**Comment by Hyper-Beast** [comment]
又是因为滥用Github Action吗，真是服了那些SB了

**Comment by EvineDeng** [comment]
是京东发邮件了

**Comment by lucifer714** [comment]
那以后都没的玩了？

**Comment by wanghlstar** [comment]
gitee 也全部下了？ 搞个组？内部的项目？

**Comment by solar24** [comment]
一早来看，全部404，天都塌了

**Comment by antsman9** [comment]
请问大佬 有没有群啥的呀？

**Comment by wanghlstar** [comment]
上次已经手动更改了码云的~~
刚把git_pull 的也改成码云了~~~~ 还能用~~

**Comment by icycofee** [comment]
> 上次已经手动更改了码云的~~
> 刚把git_pull 的也改成码云了~~~~ 还能用~~

怎么改？

**Comment by wanghlstar** [comment]
风扯呼紧 码 也下了 ，再等等了~~~~

**Comment by doghappy** [comment]
这下完了，把🐏薅成了🐐。

**Comment by jinjinv587** [comment]
> 这下完了，把🐏薅成了🐐。

笑死我了

**Comment by HengPolar** [comment]
有没有路子

**Comment by doghappy** [comment]
有没有秘密交流方式

**Comment by EvineDeng** [comment]
见docker hub

**Comment by wanghlstar** [comment]
> 见docker hub

哎~~~我还在10.13.6 ~~~ 得整个虚拟机了~~~~

**Comment by HengPolar** [comment]
docker hub在哪

**Comment by wanghlstar** [comment]
> 见docker hub

啥时候更新？ 我弄下来的镜像，进去了，发现不是最新的~~

**Comment by EvineDeng** [comment]
@lucifer714 @wanghlstar @jinjinv587 @Hyper-Beast @doghappy 

https://hub.docker.com/r/evinedeng/jd

**Comment by bigtaurus** [comment]
有没有电报方便大家交流？@EvineDeng

**Comment by wanghlstar** [comment]
> @lucifer714 @wanghlstar @jinjinv587 @Hyper-Beast @doghappy
> 
> https://hub.docker.com/r/evinedeng/jd

已收到，下载，感谢
