### ISSUE TITLE
我不能接收,为什么仓库没有

### ISSUE THREAD

**Issue by xungephp** [EvineDeng/EvineDeng#2]
呜呜呜呜呜,我不能接收,为什么仓库没有

**Comment by Kegg233** [comment]
jdbase被封掉了嘛大佬

**Comment by jinjinv587** [comment]
> jdbase被封掉了嘛大佬

我刚刚也发现了

**Comment by 5axf** [comment]
上哪能找到组织？

**Comment by huangkengwei** [comment]
啊这

**Comment by SuperManito** [comment]
唉

**Comment by Leapzhang** [comment]
大佬可以发到gitee 吗？ 这样就不会有人action执行了

**Comment by EvineDeng** [comment]
@Leapzhang @jinjinv587 @Kegg233 @huangkengwei @5axf 
https://hub.docker.com/r/evinedeng/jd

**Comment by Leapzhang** [comment]
> @Leapzhang @jinjinv587 @Kegg233 @huangkengwei @5axf
> https://hub.docker.com/r/evinedeng/jd
https://gitee.com/evine/jd-base 403受限 好像已被移除

**Comment by Leapzhang** [comment]
感谢 可以了 选择unstable版

**Comment by Kegg233** [comment]
> 感谢 可以了 选择unstable版

是docker的吗，还是gitee上的，我看了看，还是403哎

**Comment by Leapzhang** [comment]
> > 感谢 可以了 选择unstable版
> 
> 是docker的吗，还是gitee上的，我看了看，还是403哎

我是群晖里的docker 下载evinedeng/jd 会提示选择gitee还是unstable
命令行的话是docker pull evinedeng/jd:unstable

**Comment by lucifer714** [comment]
docker 版本可以多CK吗

**Comment by SuperManito** [comment]
> @Leapzhang @jinjinv587 @Kegg233 @huangkengwei @5axf
> https://hub.docker.com/r/evinedeng/jd

大佬 刚试了下 是只能跑两个号吗？我配置了3 ck 但就运行了2个号

**Comment by 794329041** [comment]
> @Leapzhang@jinjinv587@Kegg233 @huangkengwei@5axf@5axf https://hub.docker.com/r/evinedeng/jd

Fetching origin

ssh: connect to host gitee.com port 22: Connection refused


fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

error: Could not fetch origin

HEAD is now at 8c6d3ee 将Docker教程放在readme中



shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...



js脚本更新完成...
大佬 这是什么情况。。。

**Comment by SuperManito** [comment]
> > @Leapzhang@jinjinv587@Kegg233 @huangkengwei@5axf@5axf https://hub.docker.com/r/evinedeng/jd
> 
> Fetching origin
> 
> ssh: connect to host gitee.com port 22: Connection refused
> 
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> 
> and the repository exists.
> 
> error: Could not fetch origin
> 
> HEAD is now at 8c6d3ee 将Docker教程放在readme中
> 
> shell脚本更新失败，请检查原因后再次运行git_pull.sh，或等待定时任务自动再次运行git_pull.sh...
> 
> js脚本更新完成...
> 大佬 这是什么情况。。。

再执行一遍更新命令就好了

**Comment by jinjinv587** [comment]
没有映射config配置目录给本容器，请先按教程映射config配置目录...   哪位大哥知道这是怎么回事，我应该怎么弄

**Comment by jinjinv587** [comment]
> @Leapzhang @jinjinv587 @Kegg233 @huangkengwei @5axf
> https://hub.docker.com/r/evinedeng/jd

没有映射config配置目录给本容器，请先按教程映射config配置目录... 哪位大哥知道这是怎么回事，我应该怎么弄
